name: freshmart
description: FreshMart — Online Grocery Store
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0                    # API calls to FastAPI
  google_fonts: ^6.2.1            # Epilogue + Work Sans
  cached_network_image: ^3.3.1    # Smart image loading + fallback
  intl: ^0.19.0                   # Currency formatting

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # No asset folders needed — all images come from API URLs